---
title: "Simulation Diagnostics"
params:
  sim: "even_hyper_baseline"
format:
  html:
    code-fold: true
    embed-resources: true
    toc: true
    theme: flatly
execute: 
  echo: false
  warning: false
  message: false
---

Diagnostics for **`r params$sim`** simulation.

```{r}
#| label: load-libs-funcs
library(here)
source(here("utils", "check_packages.R"))
source(here("utils", "functions.R"))
```

```{r}
#| label: load-data
sim_folder = here("data", "data_constructed", "sims", params$sim)

pop <- read_csv(here(sim_folder, "final_pop.csv"))
mar <- read_csv(here(sim_folder, "final_mar.csv"))
ancestry <- read_csv(here(sim_folder, "ancestry.csv"))
```

```{r}
#| label: data-cleaning
last_year <- (max(pop$dob) - 1200) / 12

# get asfr before converting pop
asfr <- rsocsim::estimate_fertility_rates(opop = pop,
  final_sim_year = last_year, #[Jan-Dec]
  year_min = 0, # Closed [
  year_max = last_year, # Open )
  year_group = 25, 
  age_min_fert = 10, # Closed [
  age_max_fert = 55, # Open )
  age_group = 5) |> #[,)
  rename(fert_rate = socsim) |>
  filter(!is.na(year))

asmr <- rsocsim::estimate_mortality_rates(opop = pop,
  final_sim_year = last_year, #[Jan-Dec]
  year_min = 0, # Closed [
  year_max = last_year, # Open )
  year_group = 25, 
  age_max_mort = 100, # Open )
  age_group = 5) |> #[,)
  rename(mort_rate = socsim) |>
  filter(!is.na(year))

pop <- pop |>
  left_join(ancestry) |>
  mutate(sex = factor(fem, levels = 0:1, labels = c("Male", "Female")),
         mom = ifelse(mom == 0, NA, mom),
         dad = ifelse(pop == 0, NA, pop),
         dob = (dob - 1200) / 12,
         decade_birth = floor(dob / 10) * 10 + 5,
         decade_birth = ifelse(decade_birth < 0 | decade_birth > last_year,
                               NA, decade_birth),
         dod = ifelse(dod == 0, NA, (dod - 1200) / 12),
         founder = is.na(mom) & is.na(dad),
         mixedness = 1 - (ancestry_group1^2+ancestry_group2^2)) |>
  select(pid, sex, group, founder, dob, decade_birth, dod, mom, dad, 
         ancestry_group1, ancestry_group2, nearest_gen_locus, mixedness)

mar <- get_marriages(pop, mar) |>
  mutate(decade_mar = floor(year / 10) * 10 + 5,
         decade_mar = ifelse(decade_mar < 0 | decade_mar > last_year,
                             NA, decade_mar))
```

# Basic Demographic Information

## Population Pyramids

Lets start by plotting some population pyramids from the beginning of the time
period until the end of the time period. 

```{r}
#| label: fig-pop-pyramid-start
#| fig-cap: Population pyramid of the population at beginning of the simulation
plot_pop_pyramid(pop, 0)
```

```{r}
#| label: fig-pop-pyramid-50
#| fig-cap: Population pyramid of the population 150 years into the simulation.
plot_pop_pyramid(pop, 50)
```

```{r}
#| label: fig-pop-pyramid-end
#| fig-cap: Population pyramid of the population at the end of the simulation.
plot_pop_pyramid(pop, last_year)
```


## Total Population Growth

```{r}
#| label: get-total-pop-values

# by group
total_pop_group <- map(0:last_year, function(x) {
  pop |> 
    get_pop_alive(x) |> 
    group_by(group) |>
    summarize(year = x, population = n())
}) |>
  bind_rows()

# total
total_pop <- total_pop_group |>
  group_by(year) |>
  summarize(population = sum(population))

# add share to pop by group
total_pop_group <- total_pop |>
  rename(pop_total = population) |>
  right_join(total_pop_group) |>
  mutate(share = population / pop_total,
         group = factor(group)) |>
  select(year, group, population, share)
```


```{r}
#| label: fig-pop-growth
#| fig-cap: Overall size of the population from the beginning of the simulation to the end.

total_pop |>
  ggplot(aes(x = year, y = population))+
  geom_line()+
  labs(x = "years from start of simulation", y = "population size")+
  theme_bw()
```
```{r}
#| label: fig-pop-growth-rate
#| fig-cap: Annual population growth rates at 10 year intervals
# growth rates at 10 year intervals
indices <- seq(from = 1, by =10, length.out = floor(last_year / 10) + 1)
growth_rate <- (log(total_pop$population[indices[-1]]) -
                  log(total_pop$population[indices[-length(indices)]])) / 10

tibble(year = total_pop$year[indices[-1]] - 5, growth_rate) |>
  ggplot(aes(x = year, y = growth_rate))+
  geom_line()+
  geom_point()+
  scale_y_continuous(labels = scales::percent)+
  labs(x = "year (midpoint of decade)", y = "annual population growth rate")+
  theme_bw()
```

```{r}
#| label: fig-pop-growth-group
#| fig-cap: Overall size of the population from the beginning of the simulation to the end, by group.

total_pop_group |>
  ggplot(aes(x = year, y = population, group = group, color = group))+
  geom_line()+
  labs(x = "year from start of simulation", y = "population size")+
  theme_bw()
```

```{r}
#| label: fig-pop-share-group
#| fig-cap: Group share of the population from the beginning of the simulation to the end.

total_pop_group |>
  ggplot(aes(x = year, y = share, group = group, fill = group))+
  geom_area(color = "black")+
  scale_y_continuous(labels = scales::percent)+
  labs(x = "year from start of simulation", y = "share")+
  theme_bw()
```

## Fertility Rates

```{r}
#| label: fig-asfr
#| fig-cap: Age-specific fertility rates by 30 year interval
ggplot(asfr, aes(x = age, y = fert_rate, group = year, color = year))+
  geom_line()+
  labs(x = "age", y = "age-specific fertility rate", color = "year interval")+
  theme_bw()
```

```{r}
#| label: fig-tfr
#| fig-cap: Total fertility rate by 30 year interval
asfr |>
  group_by(year) |>
  summarize(tfr = sum(5 * fert_rate)) |>
  ungroup() |>
  ggplot(aes(x = year, y = tfr, group = 1))+
  geom_point()+
  geom_smooth(se = FALSE)+
  labs(x = "time period", y = "total fertility rate")+
  theme_bw()
```

## Mortality Rates

```{r}
#| label: fig-asmr
#| fig-cap: Age-specific mortality rates by 30 year interval
ggplot(asmr, aes(x = age, y = mort_rate, group = year, color = year))+
  geom_line()+
  scale_y_log10()+
  facet_wrap(~sex)+
  labs(x = "age", y = "age-specific mortality rate", color = "year interval")+
  theme_bw()
```

```{r}
#| label: fig-life-expectancy
#| fig-cap: Period life expectancy at birth by sex and time
life_exp <- asmr |> group_split(year, sex) |> map_vec(get_life_expectancy)
tibble(year = factor(rep(levels(asmr$year), each = 2), 
                     levels = levels(asmr$year)), 
       sex = rep(unique(asmr$sex), times = length(levels(asmr$year))), 
       life_exp) |>
  ggplot(aes(x = year, y = life_exp, group = sex, color = sex))+
  geom_line()+
  geom_point()+
  labs(x = "time period", y = "period life expectancy at birth")+
  theme_bw()
```

## Age at Marriage

```{r}
#| label: fig-wife-age
#| fig-cap: Distribution of wife's age at marriage
ggplot(mar, aes(x = wage))+
  geom_histogram()+
  labs(x = "wife's age at marriage")+
  theme_bw()
```

```{r}
#| label: fig-husband-age
#| fig-cap: Distribution of husband's age at marriage
ggplot(mar, aes(x = hage))+
  geom_histogram()+
  labs(x = "husband's age at marriage")+
  theme_bw()
```

```{r}
#| label: fig-spouse-age-gap
#| fig-cap: Distribution of age difference between partners
ggplot(mar, aes(x = (hage - wage)))+
  geom_histogram()+
  labs(x = "husband's age minus wife's age")+
  theme_bw()
```

# Group Mixing Information

## Intermarriage Trends

```{r}
#| label: fig-exogamy-lor
#| fig-cap: Log odds ratio of exogamy between groups over time
tab_lor <- mar |>
  calculate_lor()

ggplot(tab_lor, aes(x = decade_mar, y = lor, group = 1))+
  geom_point()+
  geom_smooth(se = FALSE)+
  labs(x = "year (in decade intervals)", y = "log odds ratio of intermarriage")+
  theme_bw()
```

```{r}
#| label: fig-exog-prop
#| fig-cap: Percent of marriages that are group exogamous over time
mar |>
  mutate(exogamous = hgroup != wgroup) |>
  group_by(decade_mar) |>
  summarize(prop_exog = mean(exogamous)) |>
  ungroup() |>
  ggplot(aes(x = decade_mar, y = prop_exog))+
  geom_point()+
  geom_smooth(se = FALSE)+
  scale_y_continuous(labels = scales::percent)+
  labs(x = "year (in decade intervals)", 
       y = "percent of unions that are group exogamous")+
  theme_bw()
```

```{r}
#| label: fig-exog-prop-group
#| fig-cap: Percent of marriages involving a member of a given group that are group exogamous over time
exog_group1 <- mar |>
  mutate(exogamous = hgroup != wgroup) |>
  filter(hgroup == 1 | wgroup == 1) |>
  group_by(decade_mar) |>
  summarize(prop_exog = mean(exogamous)) |>
  ungroup() |>
  mutate(group = 1)

exog_group <- mar |>
  mutate(exogamous = hgroup != wgroup) |>
  filter(hgroup == 2 | wgroup == 2) |>
  group_by(decade_mar) |>
  summarize(prop_exog = mean(exogamous)) |>
  ungroup() |>
  mutate(group = 2) |>
  bind_rows(exog_group1) |>
  mutate(group = factor(group))

exog_group |>
  ggplot(aes(x = decade_mar, y = prop_exog, color = group, group = group))+
  geom_point()+
  geom_smooth(se = FALSE)+
  scale_y_continuous(labels = scales::percent)+
  labs(x = "year (in decade intervals)", 
       y = "percent of unions that are group exogamous")+
  theme_bw()
```


## Ancestry Information

```{r}
#| label: get_ancestry
#| eval: false

# this just checks to make sure the ancestry data is measured the same by
# both methods, but is not run by default as it takes a long time.
parent_info <- get_parent_info(pop)
descendants <- pop |> filter(!founder)
ancestry_summary <- map(descendants$pid, get_ancestry_summary, parent_info) |>
  bind_rows() 

temp <- descendants |>
  full_join(ancestry_summary, by = "pid")

table(temp$nearest_gen_locus.x, temp$nearest_gen_locus.y, exclude = NULL)

ggplot(temp, aes(x = ancestry_group1.x, y = ancestry_group1.y))+
  geom_jitter(alpha = 0.05)
```

```{r}
#| label: fig-mean-gen-locus
#| fig-cap: Mean generational locus of mixing by decade of birth
pop |>
  group_by(decade_birth) |>
  summarize(nearest_gen_locus = mean(nearest_gen_locus, na.rm = TRUE)) |>
  ggplot(aes(x = decade_birth, y = nearest_gen_locus))+
  geom_point()+
  geom_line()+
  labs(x = "year of birth (in decade intervals)", 
       y = "mean nearest generational locus")+
  theme_bw()
```

```{r}
#| label: fig-gen-locus-dist-100
#| fig-cap: Distribution of generational locus after 200 years
pop |>
  get_pop_alive(200) |>
  ggplot(aes(x = nearest_gen_locus, y = after_stat(prop)))+
  geom_bar()+
  scale_y_continuous(labels = scales::percent)+
  labs(x = "nearest generational locus", y = NULL)+
  theme_bw()
```

```{r}
#| label: fig-gen-locus-dist-end
#| fig-cap: Distribution of generational locus at the end of the simulation
pop |>
  get_pop_alive(last_year) |>
  ggplot(aes(x = nearest_gen_locus, y = after_stat(prop)))+
  geom_bar()+
  scale_y_continuous(labels = scales::percent)+
  labs(x = "nearest generational locus", y = NULL)+
  theme_bw()
```

```{r}
#| label: fig-mean-mixedness
#| fig-cap: Mean level of mixedness by decade of birth. Mixedness is measured by Simpson's diversity index and is maximized at 0.5.
pop |>
  group_by(decade_birth) |>
  summarize(mixedness = mean(mixedness)) |>
  ggplot(aes(x = decade_birth, y = mixedness))+
  geom_point()+
  geom_line()+
  labs(x = "year of birth (in decade intervals)", 
       y = "mean level of mixedness")+
  theme_bw()
```

```{r}
#| label: fig-mixedness-locus
#| fig-cap: Distribution of mixedness by nearest generational locus. Red dots indicate exact fraction if mixing only happened ion the nearest generational locus, while blue dots indicate actual mean of mixedness by generational locus.

max_gen <- max(pop$nearest_gen_locus, na.rm = TRUE)

fractions <- pop |>
  filter(!is.na(nearest_gen_locus)) |>
  group_by(nearest_gen_locus) |>
  summarize(mixedness_actual = mean(mixedness)) |>
  ungroup() |>
  # theoretical mixedness if only one event
  mutate(mixedness_theoretical = 1-(2^(2*nearest_gen_locus)-2^(nearest_gen_locus+1)+2)/(2^(2*nearest_gen_locus)))

pop |>
  filter(!is.na(nearest_gen_locus)) |>
  ggplot(aes(x = nearest_gen_locus, y = mixedness))+
  scale_x_continuous(breaks = 1:max_gen)+
  geom_jitter(alpha = 0.01)+
  geom_point(data = fractions, (aes(y = mixedness_actual)), color = "blue", size = 2)+
  geom_point(data = fractions, (aes(y = mixedness_theoretical)), color = "red", size = 2)+
  labs(x = "nearest generational locus")+
  theme_bw()
```

```{r}
#| label: fig-nearest-locus-trend
#| fig-cap: Share of each generational locus over time
pop |>
  group_by(decade_birth) |>
  summarize(n = n(),
            punmixed = sum(is.na(nearest_gen_locus)) / n, 
            p1 = sum(nearest_gen_locus == 1, na.rm = TRUE) / n,
            p2 = sum(nearest_gen_locus == 2, na.rm = TRUE) / n,
            p3 = sum(nearest_gen_locus == 3, na.rm = TRUE) / n,
            p4plus = sum(nearest_gen_locus >= 4, na.rm = TRUE) / n) |>
  select(decade_birth, starts_with("p")) |>
  pivot_longer(cols = starts_with("p"), names_to = "group", values_to = "prop") |>
  mutate(group = factor(group, levels = c("p1", "p2", "p3", "p4plus", "punmixed"),
                        labels = c("1st gen (biracial)", "2nd gen", "3rd gen", 
                                   "4th+ gen", "Unmixed"))) |>
  ggplot(aes(x = decade_birth, y = prop, group = group, color = group))+
  geom_point(alpha = 0.3)+
  geom_smooth(se = FALSE, method = "gam", alpha = 0.7)+
  scale_y_continuous(labels = scales::percent)+
  labs(x = "year of birth (at decade intervals)", 
       y = "share of population",
       color = "generational locus")+
  theme_bw()
```


```{r}
#| label: fig-unmixed
#| fig-cap: Percent unmixed over time by group
pop |>
  group_by(decade_birth, group) |>
  summarize(n = n(),
            p_unmixed = sum(is.na(nearest_gen_locus)) / n) |>
  ungroup() |>
  mutate(group = factor(group)) |>
  select(decade_birth, group, p_unmixed) |>
  ggplot(aes(x = decade_birth, y = p_unmixed, group = group, color = group))+
  geom_line()+
  geom_point()+
  scale_y_continuous(labels = scales::percent)+
  labs(x = "year of birth (at decade intervals)", 
       y = "percent unmixed",
       color = "group")+
  theme_bw()
```
