---
title: "Check Simulations"
---

```{r}
#| label: load-libs-funcs
library(here)
source(here("utils", "check_packages.R"))
source(here("utils", "functions.R"))
```

```{r}
#| label: load-data
sim_folder <- "group2_uneven_baseline"
sim_name <- "sim_results_group2_baseline.sup_42_"
base_folder = here("simulation", "sims", sim_folder, sim_name)

pop_even_base <- read_table(here(base_folder, "result.opop"), 
                            col_names = c("pid", "fem", "group", "nev", 
                                          "dob", "mom", "dad", "nesibm", 
                                          "nesibp", "lborn", "marid", 
                                          "mstat", "dod", "fmult"))

# have to add the junk variable due to trailing zeroes
mar_even_base <- read_table(here(base_folder, "result.omar"),
                            col_names = c("mid", "wpid", "hpid", "dstart", 
                                          "dend", "rend", "wprior", "hprior", 
                                          "junk"))
```

# Basic Demographic Information

## Population Pyramids

Lets start by plotting some population pyramids from the beginning of the time
period until the end of the time period. 

```{r}
#| label: fig-pop-pyramid-even-1200
#| fig-cap: Population pyramid of the even population at beginning of the simulation
plot_pop_pyramid(pop_even_base, 1200)
```

```{r}
#| label: fig-pop-pyramid-even-1800
#| fig-cap: Population pyramid of the even population at 50 years.
plot_pop_pyramid(pop_even_base, 1800)
```

```{r}
#| label: fig-pop-pyramid-even-4800
#| fig-cap: Population pyramid of the even population at 300 years.
plot_pop_pyramid(pop_even_base, 4800)
```


## Total Population Growth

```{r}
#| label: fig-pop-growth
#| fig-cap: Overall size of the population from the beginning of the simulation to the end.
year_range <- 1200:4800

total_pop <- map_vec(year_range, function(x) {
  pop_even_base |> filter(dob <= x & (dod == 0 | dod > x)) |> nrow()
})

tibble(year_range, total_pop) |>
  mutate(year = (year_range - 1200) / 12) |>
  ggplot(aes(x = year, y = total_pop))+
  geom_line()+
  labs(x = "years from start of simulation", y = "population size")+
  theme_bw()
```

```{r}
#| label: fig-pop-growth-group
#| fig-cap: Overall size of the population from the beginning of the simulation to the end, by group.
total_pop_group <- map(year_range, function(x) {
  pop_even_base |> filter(dob <= x & (dod == 0 | dod > x)) |> 
    group_by(group) |>
    summarize(year = x, n = n())
}) |>
  bind_rows()

total_pop_group |>
  mutate(group = factor(group)) |>
  ggplot(aes(x = (year - 1200) / 12, y = n, group = group, color = group))+
  geom_line()+
  labs(x = "year from start of simulation", y = "population size")+
  theme_bw()
```

## Fertility Rates

```{r}
#| label: calculate-asfr
asfr_sim <- rsocsim::estimate_fertility_rates(opop = pop_even_base,
  final_sim_year = 300, #[Jan-Dec]
  year_min = 0, # Closed [
  year_max = 300, # Open )
  year_group = 30, 
  age_min_fert = 10, # Closed [
  age_max_fert = 55, # Open )
  age_group = 5) #[,)
```

```{r}
#| label: fig-asfr
#| fig-cap: Age-specific fertility rates by 30 year interval
ggplot(asfr_sim, aes(x = age, y = socsim, group = year, color = year))+
  geom_line()+
  labs(x = "age", y = "age-specific fertility rate", color = "year interval")+
  theme_bw()
```

```{r}
#| label: tbl-tfr
#| tbl-cap: Total fertility rate by 30 year interval
asfr_sim |>
  group_by(year) |>
    summarize(tfr = sum(5 * socsim)) |>
    gt() |>
    cols_label(year = "Year", tfr = "TFR")
```

# Group Mixing Information

## Intermarriage Trends

```{r}
#| label: get-marriages
marriages_even_base <- get_marriages(pop_even_base, mar_even_base) |>
  mutate(year = (dstart - 1200) / 12,
         time_period = cut(year, breaks = seq(from = 0, by = 20, to = 400)))
```

```{r}
#| label: fig-exogamy
#| fig-cap: Log odds ratio of exogamy between groups over time
tab_lor <- calculate_lor(marriages_even_base)

ggplot(tab_lor, aes(x = time_period, y = lor, group = 1))+
  geom_line()+
  geom_point()+
  labs(x = "time period", y = "log odds ratio of intermarriage")+
  theme_bw()
```

## Ancestry Information

```{r}
#| label: get_ancestry
parent_info <- get_parent_info(pop_even_base)
descendants <- pop_even_base |> filter(!is.na(mom))
ancestry_summary <- map(descendants$pid, get_ancestry_summary, parent_info) |>
  bind_rows()

pop_ancestry <- descendants |>
  left_join(ancestry_summary) |>
  mutate(sex = factor(fem, levels = 0:1, labels = c("Male", "Female")),
         dob = dob / 12, 
         dod = dod /12,
         mixedness = ifelse(ancestry_group1 >= ancestry_group2,
                            ancestry_group1, ancestry_group2)) |>
  select(pid, sex, group, dob, dod, starts_with("ancestry_"), 
         nearest_gen_locus, mixedness)
```

```{r}
#| label: fig-mean-gen-locus
#| fig-cap: Mean generational locus of mixing by decade of birth
pop_ancestry |>
  mutate(decade = (floor(dob / 10) * 10) - 100) |>
  group_by(decade) |>
  summarize(nearest_gen_locus = mean(nearest_gen_locus, na.rm = TRUE)) |>
  ggplot(aes(x = decade, y = nearest_gen_locus))+
  geom_point()+
  geom_line()+
  labs(x = "year", y = "mean nearest generational locus")+
  theme_bw()
```

```{r}
#| label: fig-mean-mixedness
#| fig-cap: Mean level of mixedness by decade of birth
pop_ancestry |>
  mutate(decade = (floor(dob / 10) * 10) - 100) |>
  group_by(decade) |>
  summarize(mixedness = mean(mixedness)) |>
  ggplot(aes(x = decade, y = mixedness))+
  geom_point()+
  geom_line()+
  labs(x = "year", y = "mean level of mixedness")+
  theme_bw()
```

```{r}
#| label: fig-mixedness-locus
#| fig-cap: Distribution of mixedness by nearest generational locus. Red dots indicate exact fraction if mixing only happened ion the nearest generational locus, while blue dots indicate actual mean of mixedness by generational locus.
fractions <- tibble(nearest_gen_locus = 1:10,
                    mixedness = 1-1/(2^(1:10)))

actual_fractions <- pop_ancestry |>
  group_by(nearest_gen_locus) |>
  summarize(mixedness = mean(mixedness))

pop_ancestry |>
  filter(!is.na(nearest_gen_locus)) |>
  ggplot(aes(x = nearest_gen_locus, y = mixedness))+
  scale_x_continuous(breaks = 1:10)+
  geom_jitter(alpha = 0.1)+
  geom_point(data = fractions, color = "red", size = 3)+
  geom_point(data = actual_fractions, color = "blue", size = 3)+
  theme_bw()
```

```{r}
#| label: fig-nearest-locus-trend
#| fig-cap: Share of each generational locus over time
pop_ancestry |>
  filter(dob > 100) |>
  mutate(decade = floor(dob / 10) * 10 - 100) |>
  group_by(decade) |>
  summarize(n = n(),
            punmixed = sum(is.na(nearest_gen_locus)) / n, 
            p1 = sum(nearest_gen_locus == 1, na.rm = TRUE) / n,
            p2 = sum(nearest_gen_locus == 2, na.rm = TRUE) / n,
            p3 = sum(nearest_gen_locus == 3, na.rm = TRUE) / n,
            p4plus = sum(nearest_gen_locus >= 4, na.rm = TRUE) / n) |>
  select(decade, starts_with("p")) |>
  pivot_longer(cols = starts_with("p"), names_to = "group", values_to = "prop") |>
  mutate(group = factor(group, levels = c("p1", "p2", "p3", "p4plus", "punmixed"),
                        labels = c("1st gen (biracial)", "2nd gen", "3rd gen", 
                                   "4th+ gen", "Unmixed"))) |>
  ggplot(aes(x = decade+5, y = prop, group = group, color = group))+
  geom_point(alpha = 0.3)+
  geom_smooth(se = FALSE, method = "gam", alpha = 0.7)+
  scale_y_continuous(labels = scales::percent)+
  labs(x = "year of birth (at decade intervals)", 
       y = "share of population",
       color = "generational locus")+
  theme_bw()
```
