---
title: "Simulation Diagnostics"
params:
  sim: "even_hypo_baseline"
execute: 
  echo: false
  warning: false
  message: false
---

Diagnostics for **`r params$sim`** simulation.

```{r}
#| label: load-libs-funcs
library(here)
source(here("utils", "check_packages.R"))
source(here("utils", "functions.R"))
```

```{r}
#| label: load-data
sim_folder = here("data", "data_constructed", "sims", params$sim)

pop <- read_csv(here(sim_folder, "final_pop.csv"))
mar <- read_csv(here(sim_folder, "final_mar.csv"))
ancestry <- read_csv(here(sim_folder, "ancestry.csv"))
```

```{r}
#| label: data-cleaning
last_year <- (max(pop$dob) - 1200) / 12

# get asfr before converting pop
asfr <- rsocsim::estimate_fertility_rates(opop = pop,
  final_sim_year = last_year, #[Jan-Dec]
  year_min = 0, # Closed [
  year_max = last_year, # Open )
  year_group = 30, 
  age_min_fert = 10, # Closed [
  age_max_fert = 55, # Open )
  age_group = 5) #[,)

pop <- pop |>
  left_join(ancestry) |>
  mutate(sex = factor(fem, levels = 0:1, labels = c("Male", "Female")),
         mom = ifelse(mom == 0, NA, mom),
         dad = ifelse(pop == 0, NA, pop),
         dob = (dob - 1200) / 12,
         dod = ifelse(dod == 0, NA, (dod - 1200) / 12),
         founder = is.na(mom) & is.na(dad),
         mixedness = 1 - (ancestry_group1^2+ancestry_group2^2)) |>
  select(pid, sex, group, founder, dob, dod, mom, dad, 
         ancestry_group1, ancestry_group2, nearest_gen_locus, mixedness)

mar <- get_marriages(pop, mar)
```

# Basic Demographic Information

## Population Pyramids

Lets start by plotting some population pyramids from the beginning of the time
period until the end of the time period. 

```{r}
#| label: fig-pop-pyramid-start
#| fig-cap: Population pyramid of the even population at beginning of the simulation
plot_pop_pyramid(pop, 0)
```

```{r}
#| label: fig-pop-pyramid-50
#| fig-cap: Population pyramid of the even population at 150 years.
plot_pop_pyramid(pop, 50)
```

```{r}
#| label: fig-pop-pyramid-end
#| fig-cap: Population pyramid of the even population at 300 years.
plot_pop_pyramid(pop, last_year)
```


## Total Population Growth

```{r}
#| label: fig-pop-growth
#| fig-cap: Overall size of the population from the beginning of the simulation to the end.
year_range <- 0:last_year

total_pop <- map_vec(year_range, function(x) {
  pop |> get_pop_alive(x) |> nrow()
})

tibble(year_range, total_pop) |>
  ggplot(aes(x = year_range, y = total_pop))+
  geom_line()+
  labs(x = "years from start of simulation", y = "population size")+
  theme_bw()
```

```{r}
#| label: fig-pop-growth-group
#| fig-cap: Overall size of the population from the beginning of the simulation to the end, by group.
total_pop_group <- map(year_range, function(x) {
  pop |> 
    get_pop_alive(x) |> 
    group_by(group) |>
    summarize(year = x, n = n())
}) |>
  bind_rows()

total_pop_group |>
  mutate(group = factor(group)) |>
  ggplot(aes(x = year, y = n, group = group, color = group))+
  geom_line()+
  labs(x = "year from start of simulation", y = "population size")+
  theme_bw()
```

## Fertility Rates

```{r}
#| label: fig-asfr
#| fig-cap: Age-specific fertility rates by 30 year interval
ggplot(asfr, aes(x = age, y = socsim, group = year, color = year))+
  geom_line()+
  labs(x = "age", y = "age-specific fertility rate", color = "year interval")+
  theme_bw()
```

```{r}
#| label: tbl-tfr
#| tbl-cap: Total fertility rate by 30 year interval
asfr |>
  group_by(year) |>
    summarize(tfr = sum(5 * socsim)) |>
    gt() |>
    cols_label(year = "Year", tfr = "TFR")
```

## Age at marriage

```{r}
#| label: fig-wife-age
#| fig-cap: Distribution of wife's age at marriage
ggplot(mar, aes(x = wage))+
  geom_histogram()+
  labs(x = "wife's age at marriage")+
  theme_bw()
```

```{r}
#| label: fig-husband-age
#| fig-cap: Distribution of husband's age at marriage
ggplot(mar, aes(x = hage))+
  geom_histogram()+
  labs(x = "husband's age at marriage")+
  theme_bw()
```

```{r}
#| label: fig-spouse-age-gap
#| fig-cap: Distribution of age difference between partners
ggplot(mar, aes(x = (hage - wage)))+
  geom_histogram()+
  labs(x = "husband's age minus wife's age")+
  theme_bw()
```

# Group Mixing Information

## Intermarriage Trends

```{r}
#| label: fig-exogamy
#| fig-cap: Log odds ratio of exogamy between groups over time
tab_lor <- mar |>
  mutate(time_period = cut(year, breaks = seq(from = 0, by = 20, to = last_year))) |>
  calculate_lor()

ggplot(tab_lor, aes(x = time_period, y = lor, group = 1))+
  geom_line()+
  geom_point()+
  labs(x = "time period", y = "log odds ratio of intermarriage")+
  theme_bw()
```

## Ancestry Information

```{r}
#| label: get_ancestry
#| eval: false

# this just checks to make sure the ancestry data is measured the same by
# both methods, but is not run by default as it takes a long time.
parent_info <- get_parent_info(pop)
descendants <- pop |> filter(!founder)
ancestry_summary <- map(descendants$pid, get_ancestry_summary, parent_info) |>
  bind_rows() 

temp <- descendants |>
  full_join(ancestry_summary, by = "pid")

table(temp$nearest_gen_locus.x, temp$nearest_gen_locus.y, exclude = NULL)

ggplot(temp, aes(x = ancestry_group1.x, y = ancestry_group1.y))+
  geom_jitter(alpha = 0.05)
```

```{r}
#| label: fig-mean-gen-locus
#| fig-cap: Mean generational locus of mixing by decade of birth
pop |>
  mutate(decade = floor(dob / 10) * 10) |>
  group_by(decade) |>
  summarize(nearest_gen_locus = mean(nearest_gen_locus, na.rm = TRUE)) |>
  ggplot(aes(x = decade, y = nearest_gen_locus))+
  geom_point()+
  geom_line()+
  labs(x = "year", y = "mean nearest generational locus")+
  theme_bw()
```

```{r}
#| label: fig-mean-mixedness
#| fig-cap: Mean level of mixedness by decade of birth
pop |>
  mutate(decade = floor(dob / 10) * 10) |>
  group_by(decade) |>
  summarize(mixedness = mean(mixedness)) |>
  ggplot(aes(x = decade, y = mixedness))+
  geom_point()+
  geom_line()+
  labs(x = "year", y = "mean level of mixedness")+
  theme_bw()
```

```{r}
#| label: fig-mixedness-locus
#| fig-cap: Distribution of mixedness by nearest generational locus. Red dots indicate exact fraction if mixing only happened ion the nearest generational locus, while blue dots indicate actual mean of mixedness by generational locus.

max_gen <- max(pop$nearest_gen_locus, na.rm = TRUE)

fractions <- pop |>
  filter(!is.na(nearest_gen_locus)) |>
  group_by(nearest_gen_locus) |>
  summarize(mixedness_actual = mean(mixedness)) |>
  ungroup() |>
  # theoretical mixedness if only one event
  mutate(mixedness_theoretical = 1-(2^(2*nearest_gen_locus)-2^(nearest_gen_locus+1)+2)/(2^(2*nearest_gen_locus)))

pop |>
  filter(!is.na(nearest_gen_locus)) |>
  ggplot(aes(x = nearest_gen_locus, y = mixedness))+
  scale_x_continuous(breaks = 1:max_gen)+
  geom_jitter(alpha = 0.01)+
  geom_point(data = fractions, (aes(y = mixedness_actual)), color = "blue", size = 2)+
  geom_point(data = fractions, (aes(y = mixedness_theoretical)), color = "red", size = 2)+
  theme_bw()
```

```{r}
#| label: fig-nearest-locus-trend
#| fig-cap: Share of each generational locus over time
pop |>
  mutate(decade = floor(dob / 10) * 10) |>
  filter(decade >= 0) |>
  group_by(decade) |>
  summarize(n = n(),
            punmixed = sum(is.na(nearest_gen_locus)) / n, 
            p1 = sum(nearest_gen_locus == 1, na.rm = TRUE) / n,
            p2 = sum(nearest_gen_locus == 2, na.rm = TRUE) / n,
            p3 = sum(nearest_gen_locus == 3, na.rm = TRUE) / n,
            p4plus = sum(nearest_gen_locus >= 4, na.rm = TRUE) / n) |>
  select(decade, starts_with("p")) |>
  pivot_longer(cols = starts_with("p"), names_to = "group", values_to = "prop") |>
  mutate(group = factor(group, levels = c("p1", "p2", "p3", "p4plus", "punmixed"),
                        labels = c("1st gen (biracial)", "2nd gen", "3rd gen", 
                                   "4th+ gen", "Unmixed"))) |>
  ggplot(aes(x = decade+5, y = prop, group = group, color = group))+
  geom_point(alpha = 0.3)+
  geom_smooth(se = FALSE, method = "gam", alpha = 0.7)+
  scale_y_continuous(labels = scales::percent)+
  labs(x = "year of birth (at decade intervals)", 
       y = "share of population",
       color = "generational locus")+
  theme_bw()
```


```{r}
pop |>
  mutate(decade = floor(dob / 10) * 10) |>
  filter(decade >= 0) |>
  group_by(decade, group) |>
  summarize(n = n(),
            p_unmixed = sum(is.na(nearest_gen_locus)) / n) |>
  ungroup() |>
  mutate(group = factor(group)) |>
  select(decade, group, p_unmixed) |>
  ggplot(aes(x = decade, y = p_unmixed, group = group, color = group))+
  geom_line()+
  geom_point()+
  scale_y_continuous(labels = scales::percent)+
  labs(x = "year of birth (at decade intervals)", 
       y = "percent unmixed",
       color = "group")+
  theme_bw()
```
