---
title: "Organize Data Notebook"
---

```{r}
#| label: setup
#| include: false
library(here)
source(here("utils","check_packages.R"))
source(here("utils","functions.R"))
```

This quarto doc is used to organize the data.

```{r}
#| label: load-data

## high results ##
sim_folder <- "group2_even_high"
sim_name <- "sim_results_group2_high.sup_42_"
base_folder = here("simulation", "sims", sim_folder, sim_name)

pop_even_high <- read_table(here(base_folder, "result.opop"), 
                            col_names = c("pid", "fem", "group", "nev", 
                                          "dob", "mom", "dad", "nesibm", 
                                          "nesibp", "lborn", "marid", 
                                          "mstat", "dod", "fmult"))

# have to add the junk variable due to trailing zeroes
mar_even_high <- read_table(here(base_folder, "result.omar"),
                            col_names = c("mid", "wpid", "hpid", "dstart", 
                                          "dend", "rend", "wprior", "hprior", 
                                          "junk"))

sim_folder <- "group2_uneven_high"
base_folder = here("simulation", "sims", sim_folder, sim_name)

pop_uneven_high <- read_table(here(base_folder, "result.opop"), 
                              col_names = c("pid", "fem", "group", "nev", 
                                            "dob", "mom", "dad", "nesibm", 
                                            "nesibp", "lborn", "marid", 
                                            "mstat", "dod", "fmult"))

mar_uneven_high <- read_table(here(base_folder, "result.omar"),
                              col_names = c("mid", "wpid", "hpid", "dstart", 
                                            "dend", "rend", "wprior", "hprior", 
                                            "junk"))

sim_folder <- "group2_highly_uneven_high"
base_folder = here("simulation", "sims", sim_folder, sim_name)

pop_highly_uneven_high <- read_table(here(base_folder, "result.opop"), 
                                     col_names = c("pid", "fem", "group", "nev", 
                                                   "dob", "mom", "dad", "nesibm", 
                                                   "nesibp", "lborn", "marid", 
                                                   "mstat", "dod", "fmult"))

# have to add the junk variable due to trailing zeroes
mar_highly_uneven_high <- read_table(here(base_folder, "result.omar"),
                                     col_names = c("mid", "wpid", "hpid", 
                                                   "dstart", "dend", "rend", 
                                                   "wprior", "hprior",
                                                   "junk"))

## low results ##
sim_folder <- "group2_even_low"
sim_name <- "sim_results_group2_low.sup_42_"
base_folder = here("simulation", "sims", sim_folder, sim_name)

pop_even_low <- read_table(here(base_folder, "result.opop"), 
                           col_names = c("pid", "fem", "group", "nev", 
                                         "dob", "mom", "dad", "nesibm", 
                                         "nesibp", "lborn", "marid", 
                                         "mstat", "dod", "fmult"))

# have to add the junk variable due to trailing zeroes
mar_even_low <- read_table(here(base_folder, "result.omar"),
                           col_names = c("mid", "wpid", "hpid", "dstart", 
                                         "dend", "rend", "wprior", "hprior", 
                                         "junk"))

sim_folder <- "group2_uneven_low"
base_folder = here("simulation", "sims", sim_folder, sim_name)

pop_uneven_low <- read_table(here(base_folder, "result.opop"), 
                             col_names = c("pid", "fem", "group", "nev", 
                                           "dob", "mom", "dad", "nesibm", 
                                           "nesibp", "lborn", "marid", 
                                           "mstat", "dod", "fmult"))

mar_uneven_low <- read_table(here(base_folder, "result.omar"),
                             col_names = c("mid", "wpid", "hpid", "dstart", 
                                           "dend", "rend", "wprior", "hprior", 
                                           "junk"))

sim_folder <- "group2_highly_uneven_low"
base_folder = here("simulation", "sims", sim_folder, sim_name)

pop_highly_uneven_low <- read_table(here(base_folder, "result.opop"), 
                                    col_names = c("pid", "fem", "group", "nev", 
                                                  "dob", "mom", "dad", "nesibm", 
                                                  "nesibp", "lborn", "marid", 
                                                  "mstat", "dod", "fmult"))

# have to add the junk variable due to trailing zeroes
mar_highly_uneven_low <- read_table(here(base_folder, "result.omar"),
                                    col_names = c("mid", "wpid", "hpid", 
                                                  "dstart", "dend", "rend", 
                                                  "wprior", "hprior",
                                                  "junk"))
```

```{r}
#| label: code-marriages

mar_even_high <- get_marriages(pop_even_high, mar_even_high)
mar_uneven_high <- get_marriages(pop_uneven_high, mar_uneven_high)
mar_highly_uneven_high <- get_marriages(pop_highly_uneven_high, 
                                        mar_highly_uneven_high)
mar_even_low <- get_marriages(pop_even_low, mar_even_low)
mar_uneven_low <- get_marriages(pop_uneven_low, mar_uneven_low)
mar_highly_uneven_low <- get_marriages(pop_highly_uneven_low, 
                                        mar_highly_uneven_low)
```

```{r}
#| label: add-ancestry-info

system.time(x <- map(pop_even_high$pid, get_ancestry_summary, get_parent_info(pop_even_high)))
pop_even_high <- add_ancestry_info(pop_even_high)
pop_uneven_high <- add_ancestry_info(pop_uneven_high)
pop_highly_uneven_high <- add_ancestry_info(pop_highly_uneven_high)
pop_even_low <- add_ancestry_info(pop_even_low)
pop_uneven_low <- add_ancestry_info(pop_uneven_low)
pop_highly_uneven_low <- add_ancestry_info(pop_highly_uneven_low)
```
