---
title: "The Dynamics of Population Mixing: A Simulation Approach"
shorttitle: Dynamics of Population Mixing
shortauthors: Gullickson and Saperstein
#keywords:
#  - keyword1
#  - keyword2
#thanks: Prepared for the 2026 Annual Meeting Population Association of America, St. Louis, Missouri
filters:
  - abstract-section
format:
  aog-article-pdf:
    keep-tex: false
    fig-pos: "!tb"
---

```{r}
#| label: setup
#| include: false
library(here)
source(here("utils","check_packages.R"))
source(here("utils","functions.R"))
load(here("data", "data_constructed", "analytical_data.RData"))

years_runin <- 100
```

```{r}
#| label: set-palettes

palette_scenario <- c(
  "absorbing state"      = "#E7298A",  
  "high peak, resilient" = "#2C7FB8",  
  "high peak, decay"     = "#66C2A5", 
  "low peak, resilient"  = "#D95F02", 
  "low peak, decay"      = "#FDB462"  
)

palette_group <- c(
  "A"  = "#000080",
  "B"  = "#FF6347",
  "AB" = "#FFD700"
)

palette_intermar <- c(
  "B-AB"  = "#00A6A6",
  "A-AB"  = "#F18F01",
  "A-B"   = "#5F0F40"
)

palette_mar_growth <- c(
  "progress" = "#1B4332",
  "plateau"  = "#C9184A"
)
```


```{r}
#| label: clean-up-labels

sims_pop <- sims_pop |>
  mutate(
    group = factor(group, levels = 1:3, labels = c("A", "B", "AB")),
    pop_share = factor(pop_share, levels = c("uneven", "even"), 
                       labels = c("uneven (85/15)", "even (50/50)")),
    scenario = str_replace(scenario, "_", " peak, "),
    scenario = str_replace(scenario, "total peak, rigid", "absorbing state"),
    scenario = factor(
      scenario,
      levels = c("absorbing state", "high peak, resilient", "high peak, decay",
                 "low peak, resilient", "low peak, decay")))
```

```{r}
#| label: count-pop-group
#| include: false

total_pop_group <- map(years_runin:(years_runin + 200), function(x) {
  sims_pop |>
    get_pop_alive(x) |>
    group_by(group, pop_share, mar_growth, scenario) |>
    summarize(year = x, population = n(), .groups = "drop") |>
    group_by(pop_share, mar_growth, scenario) |>
    mutate(share = population / sum(population)) |>
    arrange(pop_share, mar_growth, scenario, group)
}) |>
  bind_rows()

total_pop_ancestry <- map(years_runin:(years_runin + 200), function(x) {
  sims_pop |>
    get_pop_alive(x) |>
    group_by(pop_share, mar_growth, scenario) |>
    summarize(year = x, 
              share_mixed = mean(ancestry_group1 < 1 & ancestry_group2 < 1), 
              .groups = "drop") |>
    arrange(pop_share, mar_growth, scenario)
}) |>
  bind_rows()
```

{{< include main_manuscript.md >}}

```{r}
#| label: fig-marriage-lor
#| fig-cap: Estimated log odds ratio of an intergroup union  over time in five year intervals, across scenario types. Smoothed lines are estimated across classification scenarios via a Generalized Additive Model (GAM). 

mar_summary <- sims_mar |>
  filter(year >= years_runin) |>
  mutate(year = year - years_runin) |>
  mutate(year5 = floor(year/5)*5+2.5) |>
  group_by(year5, pop_share, mar_growth, scenario) |>
  summarize(n11 = sum(hgroup == 1 & wgroup == 1),
            n22 = sum(hgroup == 2 & wgroup == 2),
            n33 = sum(hgroup == 3 & wgroup == 3),
            n12 = sum(hgroup == 1 & wgroup == 2),
            n21 = sum(hgroup == 2 & wgroup == 1),
            n13 = sum(hgroup == 1 & wgroup == 3),
            n31 = sum(hgroup == 3 & wgroup == 1),
            n23 = sum(hgroup == 2 & wgroup == 3),
            n32 = sum(hgroup == 3 & wgroup == 2),
            lor12 = log(n12) + log(n21) - log(n11) - log(n22),
            lor13 = log(n13) + log(n31) - log(n11) - log(n33),
            lor23 = log(n23) + log(n32) - log(n22) - log(n33),
            out_all = (n12+n21+n13+n31+n23+n32)/(n11+n22+n33+n12+n21+n13+n31+n23+n32),
            out1 = (n12+n21+n13+n31)/(2*n11+n12+n21+n13+n31),
            out2 = (n12+n21+n23+n32)/(2*n22+n12+n21+n23+n32),
            out3 = (n13+n23+n23+n32)/(2*n33+n13+n23+n23+n32)) |>
  mutate(lor12 = if_else(is.na(lor12) | lor12 == Inf | lor12 == -Inf, NA, lor12),
         lor13 = if_else(is.na(lor13) | lor13 == Inf | lor13 == -Inf, NA, lor13),
         lor23 = if_else(is.na(lor23) | lor23 == Inf | lor23 == -Inf, NA, lor23),
         mar_growth = factor(mar_growth, levels = c("progress", "plateau")),
         pop_share = factor(pop_share, levels = c("even", "uneven")),
         scenario = str_replace(scenario, "_", " peak, "),
         scenario = str_replace(scenario, "total peak, rigid", "absorbing state"),
         scenario = factor(
           scenario,
           levels = c("absorbing state", "high peak, resilient", "high peak, decay",
                      "low peak, resilient", "low peak, decay"))) |>
  select(year5, pop_share, mar_growth, scenario, starts_with("lor"), 
         starts_with("out"))

mar_summary |>
  pivot_longer(cols = starts_with("lor"), names_prefix = "lor", 
               names_to = "type", values_to = "lor") |>
  mutate(type = case_when(type == "12" ~ "A-B",
                          type == "13" ~ "A-AB",
                          type == "23" ~ "B-AB"),
         type = factor(type, levels = c("A-B", "A-AB", "B-AB")),
         pop_share = factor(pop_share, levels = c("uneven", "even"), 
                       labels = c("uneven (85/15)", "even (50/50)"))) |>
  ggplot(aes(year5, lor, group = type, color = type, shape = scenario))+
  geom_hline(yintercept = c(-10, 0), linetype = 2)+
  geom_point(alpha = 0.3)+
  geom_smooth(se = FALSE, method = "gam")+
  facet_grid(pop_share~mar_growth)+
  scale_color_manual(values = palette_intermar)+
  scale_shape_manual(values = c(19, 15, 17, 18, 3))+
  #scale_y_continuous(limits = c(-10, 0.1))+
  labs(y = "log odds ratio of intergroup union",
       x = "year of union",
       shape = "classification\nscenario",
       color = "pairing")+
  theme_bw()
```


```{r}
#| label: fig-scenarios
#| fig-cap: Four group assignment scenarios for individuals of mixed parentage as a function of the proportion of their group A ancestry

calculate_probs <- function(scenario_name) {
  parameters <- range_read(
    "1ad-fJUCjRy_zslI2MMce8UaolepG536-IZr1yNNIuZ8",
    range = paste(scenario_name, "A8:L9", sep="!")
  ) |>
    select(starts_with("inherit"))
  prop_a <- seq(from = 0.01, to= 0.99, by = 0.01)
  y_a <- parameters$inherit_g1_intercept+
    parameters$inherit_g1_slope*prop_a+
    parameters$inherit_g1_slope_sq*(prop_a^2)+
    parameters$inherit_g1_slope_cube*(prop_a^3)
  y_b <- parameters$inherit_g2_intercept+
    parameters$inherit_g2_slope*prop_a+
    parameters$inherit_g2_slope_sq*(prop_a^2)+
    parameters$inherit_g2_slope_cube*(prop_a^3)
  y_ab <- 0 * prop_a
  denom <- (exp(y_a)+exp(y_b)+exp(y_ab))
  p_a <- exp(y_a)/denom
  p_b <- exp(y_b)/denom
  p_ab <- exp(y_ab)/denom
  
  tibble(group = factor(rep(c("A", "B", "AB"), each = length(prop_a)),
                        levels = c("A", "B", "AB")),
         prop_a = rep(prop_a, 3), 
         prob = c(p_a, p_b, p_ab))
}

gs4_deauth()

# high resilient
gp_hr <- calculate_probs("uneven_plateau_high_resilient") |>
  mutate(scenario_peak = "high peak", scenario_decline = "resilient")

# high decay
gp_hd <- calculate_probs("uneven_plateau_high_decay") |>
  mutate(scenario_peak = "high peak", scenario_decline = "decay")

# low resilient
gp_lr <- calculate_probs("uneven_plateau_low_resilient") |>
  mutate(scenario_peak = "low peak", scenario_decline = "resilient")

# low decay
gp_ld <- calculate_probs("uneven_plateau_low_decay") |>
  mutate(scenario_peak = "low peak", scenario_decline = "decay")

bind_rows(gp_hr, gp_hd, gp_lr, gp_ld) |>
  mutate(scenario_decline = factor(scenario_decline, 
                                   levels = c("resilient", "decay"))) |>
  ggplot(aes(x = prop_a, y = prob, group = group, color = group))+
  geom_line(size = 1)+
  facet_grid(scenario_decline~scenario_peak)+
  scale_y_continuous(labels = scales::percent, limits = c(0, 1))+
  scale_color_manual(values = palette_group)+
  labs(x = "proportion group A ancestry", 
       y = "probability of group assignment")+
  theme_bw()
```


```{r}
#| label: fig-biracial-pop-scenario
#| fig-cap: The share of the population identified as mixed (AB), over time and across scenarios

total_pop_group |>
  filter(group == "AB") |>
  mutate(year = year - years_runin) |>
  ggplot(aes(x = year, y = share, group = scenario, color = scenario))+
  geom_line(linewidth = 1, alpha = 0.7)+
  facet_grid(pop_share~mar_growth)+
  scale_y_continuous(labels = scales::percent)+
  scale_color_manual(values = palette_scenario)+
  labs(y = "share of population identifying as mixed (AB)",
       color = "classification\nscenario")+
  theme_bw()
```


```{r}
#| label: fig-mixed-ancestry-share-time
#| fig-cap: The share of the population with mixed ancestry regardless of identification, over time and across scenarios

total_pop_ancestry |>
  mutate(year = year - years_runin) |>
  ggplot(aes(x = year, y = share_mixed, group = scenario, color = scenario))+
  geom_line(linewidth = 1, alpha = 0.5)+
  facet_grid(pop_share~mar_growth)+
  scale_y_continuous(labels = scales::percent)+
  scale_color_manual(values = palette_scenario)+
  labs(y = "share of population with mixed ancestry",
       color = "classification\nscenario")+
  theme_bw()
```

```{r}
#| label: fig-biracial-share-scenario
#| fig-cap: The size of the self-identified mixed (AB) population at the conclusion of the simulation as a fraction of all individuals with some mixed ancestry

sims_pop |>
  # get everyone living at the end
  filter(is.na(dod)) |>
  # leave out absorbing state
  filter(scenario != "absorbing state") |>
  # only those who have mixed ancestry
  filter(ancestry_group1 < 1 & ancestry_group2 < 1) |>
  group_by(pop_share, mar_growth, scenario) |>
  summarize(p_identify_mixed = mean(group == "AB"), .groups = "drop") |>
  ggplot(aes(x = fct_rev(scenario), y = p_identify_mixed, group = mar_growth,
             color = mar_growth))+
  geom_segment(aes(yend = 0), position = position_dodge(width = 0.6))+
  geom_point(position = position_dodge(width = 0.6))+
  #geom_hline(yintercept = c(0.4, 0.75), linetype = 3)+
  facet_wrap(~pop_share)+
  coord_flip()+
  scale_y_continuous(labels = scales::percent, limits = c(0, 1))+
  scale_color_manual(values = palette_mar_growth)+
  labs(y = "Size of mixed (AB) population as fraction of all individuals with mixed ancestry",
       x = NULL,
       color = "partnering\ntrend")+
  theme_bw()
```


```{r}
#| label: fig-ancestry-distribution
#| fig-cap: Distribution of share of Group A ancestry among those who have mixed ancestry at the end of the simulation. Distribution is estimated and smoothed using kernel density. Dotted vertical lines indicate the starting share of Group A population in each scenario. 

starting_pop <- tibble(
  share_a = c(0.85, 0.5),
  pop_share = levels(sims_pop$pop_share), levels = levels(sims_pop$pop_share)
)

sims_pop |>
  filter(scenario != "absorbing state") |>
  # get everyone living at the end
  filter(is.na(dod)) |>
  # only those who have mixed ancestry
  filter(ancestry_group1 < 1 & ancestry_group2 < 1) |>
  ggplot(aes(x = ancestry_group1, 
             y = after_stat(density),
             fill = mar_growth))+
  geom_density(alpha = 0.5, adjust = 2)+
  geom_vline(data = starting_pop, aes(xintercept = share_a), linetype = 3)+
  facet_grid(pop_share~scenario)+
  scale_x_continuous(breaks = c(0, 0.5, 1), labels = scales::percent)+
  scale_fill_manual(values = palette_mar_growth)+
  labs(x = "share of group A ancestry",
       fill = "partnering\ntrend")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45,hjust = 1))
  
```




```{r}
#| label: fig-group-dist
#| fig-cap: The distribution of groups over time, across different classification scenarios. All cases use the "progress" scenario for intergroup partnering.
#| fig-height: 8
#| fig-pos: "p"

total_pop_group |>
  filter(mar_growth == "progress") |>
  mutate(year = year - years_runin) |>
  ggplot(aes(x = year, y = share, fill = group))+
  facet_grid(scenario~pop_share)+
  geom_area(color = NA)+
  scale_fill_manual(values = palette_group)+
  scale_y_continuous(labels = scales::percent)+
  labs(y = NULL)+
  theme_bw()+
  theme(panel.grid = element_blank(), panel.grid.major.x = element_blank())
          
```


```{r}
#| label: fig-out-marriage
#| fig-cap: Estimated share of all unions that are A-B intergroup unions over time by initial group size and scenario. Smoothed lines are estimated via GAM. 

mar_summary <- sims_mar |>
  filter(year >= years_runin) |>
  mutate(year = year - years_runin) |>
  mutate(decade = floor(year/10)*10+5) |>
  group_by(year, pop_share, mar_growth, scenario) |>
  summarize(n11 = sum(hgroup == 1 & wgroup == 1),
            n22 = sum(hgroup == 2 & wgroup == 2),
            n33 = sum(hgroup == 3 & wgroup == 3),
            n12 = sum(hgroup == 1 & wgroup == 2),
            n21 = sum(hgroup == 2 & wgroup == 1),
            n13 = sum(hgroup == 1 & wgroup == 3),
            n31 = sum(hgroup == 3 & wgroup == 1),
            n23 = sum(hgroup == 2 & wgroup == 3),
            n32 = sum(hgroup == 3 & wgroup == 2),
            lor12 = log(n12) + log(n21) - log(n11) - log(n22),
            lor13 = log(n13) + log(n31) - log(n11) - log(n33),
            lor23 = log(n23) + log(n32) - log(n22) - log(n33),
            out_all = (n12+n21+n13+n31+n23+n32)/(n11+n22+n33+n12+n21+n13+n31+n23+n32),
            out1 = (n12+n21+n13+n31)/(2*n11+n12+n21+n13+n31),
            out2 = (n12+n21+n23+n32)/(2*n22+n12+n21+n23+n32),
            out3 = (n13+n23+n23+n32)/(2*n33+n13+n23+n23+n32),
            out12 = (n12+n21)/((n11+n22+n33+n12+n21+n13+n31+n23+n32))) |>
  mutate(mar_growth = factor(mar_growth, levels = c("plateau", "progress")),
         pop_share = factor(pop_share, levels = c("uneven", "even"),
                            labels = c("uneven (85/15)", "even (50/50)")),
         scenario = str_replace(scenario, "_", " peak, "),
         scenario = str_replace(scenario, "total peak, rigid", "absorbing state"),
         scenario = factor(
           scenario,
           levels = c("absorbing state", "high peak, resilient", "high peak, decay",
                      "low peak, resilient", "low peak, decay")))
         

ggplot(mar_summary, aes(year, out12, group = scenario, color = scenario))+
  geom_smooth(se = FALSE, method = "gam")+
  facet_grid(pop_share~mar_growth)+
  scale_color_manual(values = palette_scenario)+
  scale_y_continuous(labels = scales::percent)+
  labs(y = "Share of all unions that are A-B intergroup unions",
       color = "classification/scenario")+
  theme_bw()
```


```{r}
#| label: fig-mixed-ancestry-share-scenario
#| fig-cap: The share of the population that has mixed ancestry at the end of the simulation
#| eval: false
sims_pop |>
  filter(is.na(dod)) |>
  group_by(pop_share, mar_growth, scenario) |>
  summarize(p_mixed = mean(ancestry_group1 < 1 & ancestry_group2 < 1)) |>
  ungroup() |>
  ggplot(aes(x = scenario, y = p_mixed, group = mar_growth, color = mar_growth))+
  geom_segment(aes(yend = 0), position = position_dodge(width = 0.6))+
  geom_point(position = position_dodge(width = 0.6))+
  facet_wrap(~pop_share)+
  coord_flip()+
  scale_y_continuous(labels = scales::percent, limits = c(0, 1))+
  scale_color_manual(values = palette_mar_growth)+
  labs(y = "Share of population that has mixed ancestry",
       x = NULL,
       color = "partnership\ntrend")+
  theme_bw()

```


